reordered imports
nexB/scancode-server pull request #109
Opened 2018-01-20 22:16 UTC by srbcheema1

this PR fixes the #57 issue .
i have reordered the imports in lexicographical order .

2018-01-31 19:27 UTC, singh1114 requested changes

2018-01-31 19:27 UTC, singh1114 commented on scanapp/admin.py
>  from scanapp.models import Copyright
Use it as follows:
```
from scanapp.models import (
    Copyright, CopyrightAuthor .....
)
```

2018-01-31 19:27 UTC, singh1114 commented on scanapp/serializers.py
>  from scanapp.models import Copyright
Similar things will work.

2018-01-31 19:27 UTC, singh1114 commented on scanapp/urls.py
>  from scanapp.views import LoginView
Same with this. You can dig more files and use the same procedure.

2018-02-01 06:39 UTC, singh1114 requested changes

2018-02-01 06:39 UTC, singh1114 commented on scanapp/urls.py
> +    LocalUploadView, LoginView, RedirectView, ScanApiView, UrlScanView
It's `RegisterView` not `RedirectView`.

2018-02-01 14:47 UTC, srbcheema1 commented
@singh1114 that was my typo mistake. I have applied the changes requested and amended into last commit. please review

2018-02-02 14:50 UTC, singh1114 commented
Check why travis-CI is not working.

2018-02-05 05:26 UTC, srbcheema1 commented
@singh1114 travis-CI tests passed, please review

2018-02-06 04:20 UTC, singh1114 approved these changes

2018-02-06 04:21 UTC, singh1114 commented
@srbcheema1 Good work!

2018-02-06 04:28 UTC, srbcheema1 commented
thanks @singh1114 I would love to contribute more.

2018-02-06 04:31 UTC, singh1114 commented
@srbcheema1  Surely.

2018-02-06 20:44 UTC, pombredanne commented
@srbcheema1 can you add a sign off to your commits or at least to the PR comment?

2018-02-06 20:46 UTC, pombredanne requested changes
Thank you! Please see my comments

2018-02-06 20:46 UTC, pombredanne commented on scanapp/admin.py
> +)
I am sorry but I do not like this style of imports at all, can you use the same style we use elsewhere?

2018-02-06 20:46 UTC, pombredanne commented on scanapp/serializers.py
Same comment as above, one import per line is what I prefer,

2018-02-07 07:18 UTC, srbcheema1 commented
@pombredanne  I have made the requested changes. Please have a look

2018-02-07 07:24 UTC, pombredanne commented
Thanks! do you mind to squash these commits in one?

2018-02-07 09:06 UTC, singh1114 commented
@pombredanne We can squash while merging.

2018-02-07 14:30 UTC, srbcheema1 commented
@pombredanne  please have a look at it

2018-02-07 14:40 UTC, pombredanne commented
Thanks! can you add your signoff and reword your message to use the imperative style? See https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages

2018-02-07 15:08 UTC, pombredanne commented
Much better! imperative style for the subject line would be instead: `Reorder imports` and `Removes trailing white spaces` instead... think of it like if you are giving an order to the codebase to update thyself!

2018-02-07 15:28 UTC, srbcheema1 commented
@pombredanne I will take care of naming in future. Thanks for this.

2018-02-07 16:38 UTC, pombredanne commented
LGTM. Thank you!

2018-02-07 16:38 UTC, merged

2018-02-07 17:18 UTC, srbcheema1 commented
Thanks @pombredanne 
I am glad to see my first PR merged in this organisation. 
I would love to contribute more in this organization.