Integrated login module
nexB/scancode-server pull request #42
Opened 2017-07-04 10:26 UTC by RajuKoushik

Signed-off-by: Raju Koushik g.rajukoushik@gmail.com

2017-07-04 10:31 UTC, singh1114 requested changes
Not acceptable. Add at least something into the files. Put css in the login.html to the css file and javascript to login.js file.

2017-07-04 10:53 UTC, singh1114 requested changes

2017-07-04 10:53 UTC, singh1114 commented on scanapp/templates/scanapp/login.html
>  <html>
No need for this.

2017-07-04 10:53 UTC, singh1114 commented on scanapp/templates/scanapp/login.html
>  <head>
Same here. Check how is it done in index.html

2017-07-04 10:53 UTC, singh1114 commented on scanapp/templates/scanapp/login.html
>  </head>
This is in the base.html.

2017-07-04 10:53 UTC, singh1114 commented on scanapp/templates/scanapp/login.html
> +<script src="{% static "javascript/login.js" %}"></script>
scripts don't get loaded this way.

2017-07-04 10:54 UTC, RajuKoushik commented on scanapp/templates/scanapp/login.html
> +<script src="{% static "javascript/login.js" %}"></script>
Did you run the code @singh1114 . Coz it's running fine and the script works

2017-07-04 11:08 UTC, RajuKoushik commented on scanapp/templates/scanapp/login.html
> +<script src="{% static "javascript/login.js" %}"></script>
Updates the changes @singh1114

2017-07-04 11:10 UTC, singh1114 commented on scanapp/templates/scanapp/login.html
> +<script src="{% static "javascript/login.js" %}"></script>
Ok. Just wait till I remove every bad code and then I will test locally.

2017-07-04 11:11 UTC, RajuKoushik commented on scanapp/templates/scanapp/login.html
> +<script src="{% static "javascript/login.js" %}"></script>
cool

2017-07-05 10:13 UTC, singh1114 commented on scanapp/views.py
>  def login(request):
Use class based views.

2017-07-05 10:14 UTC, singh1114 commented on scanapp/views.py
> +def post_sign_up(request):
Use class-based views. We don't want to add csrf_exception for this view. Do we?

2017-07-05 13:06 UTC, RajuKoushik commented on scanapp/views.py
> +def post_sign_up(request):
I'll use the class based views but we need the csrf exemt. Just check the docs.

2017-07-05 14:45 UTC, RajuKoushik commented
@singh1114  just updated with the class based views.

2017-07-05 20:46 UTC, singh1114 requested changes

2017-07-05 20:46 UTC, singh1114 commented on scancodeserver/settings.py
> +        'NAME': 'taskbuster_db',
BAD. Check before committing.

2017-07-05 20:46 UTC, singh1114 commented on scanapp/views.py
> +            # user.last_name = request.POST.get('last_name', '')
Remove these extra comments.

2017-07-05 20:48 UTC, RajuKoushik commented on scancodeserver/settings.py
> +        'NAME': 'taskbuster_db',
Fixed it in the minor glitch commit.

2017-07-05 20:51 UTC, RajuKoushik commented on scanapp/views.py
> +            # user.last_name = request.POST.get('last_name', '')
Done !

2017-07-05 21:32 UTC, merged