Add unit tests for models
nexB/scancode-server pull request #44
Opened 2017-07-05 18:22 UTC by singh1114

* Add unit tests for models
* Change models according to the unit tests
* Remove `CeleryScan` model class

Signed-off-by: Ranvir Singh ranvir.singh1114@gmail.com

2017-07-12 08:04 UTC, pombredanne requested changes
This starts looking good. We need to have a good discussion on models. There are too many of them IMHO. Also do not add meta unless really needed. 
Finally please check vulnerable code and enable the code styles checks ... I have activated Travis on the repo now... so https://travis-ci.org/nexB/scancode-server will show the test runs.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'Scan Info'
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'User Info'
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +    class Meta:
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'Local Scan Info'
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +    class Meta:
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'Scan File Info'
This meta is not needed IMHO. Also why do you suffix all your models with `Info`?if these are objects they represent something not SomethingInfo

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'Licenses'
This meta is not needed IMHO.

2017-07-12 08:04 UTC, pombredanne commented on scanapp/models.py
> +        verbose_name_plural = 'Matched Rule'
This meta is not needed IMHO. And this is not plural

2017-07-12 08:04 UTC, pombredanne commented on scanapp/tests/test_tasks.py
> +import json
Typically the `json` import which is stdlib should come before django imports that are from a third-party

2017-07-12 08:04 UTC, pombredanne commented on scanapp/tests/test_tasks.py
> +        URL='https://github.com/'
The spacing around equal is not right.

2017-07-12 10:08 UTC, singh1114 commented on scanapp/tests/test_tasks.py
> +        URL='https://github.com/'
OK.

2017-07-31 10:34 UTC, pombredanne reviewed
Looking good at a high level. I did not yet review the tests in details...
Now avoid to keep commented out code... Either you have the code and the test pass or fails or you do not keep the code as comment... I guess here this is just because you still have some things to refine on the testing side once merged?

2017-07-31 12:16 UTC, merged