Create POST API endpoint to ScanCode given GitHub or BitBucket or Git…
nexB/scancode-server pull request #61
Opened 2017-07-18 21:54 UTC by RajuKoushik

… URL.

Fixed issue #52
Signed-off-by: Raju Koushik g.rajukoushik@gmail.com

2017-07-23 11:59 UTC, pombredanne commented on scanapp/forms.py
> +class UrlSpecialScanForm(forms.Form):
Why create a new form?

2017-07-23 17:14 UTC, RajuKoushik commented on scanapp/forms.py
> +class UrlSpecialScanForm(forms.Form):
@pombredanne  I had a discussion with @singh1114  where we planned to have a new view for the URL Scan and keep the URLSpecialScan intact for testing purposes which we would be removing after the main view is created.

2017-07-23 17:49 UTC, pombredanne requested changes
I added some comments. You are missing some basic doc strings for the key functions which should be externalized to be testable separately and there are no tests at all. we need tests.

2017-07-23 17:49 UTC, pombredanne commented on scanapp/models.py
> -        return self.total_code_files
Why do you include model changes in this PR?

2017-07-23 17:49 UTC, pombredanne commented on scanapp/views.py
> +
Please organize your import correctly

2017-07-23 17:49 UTC, pombredanne commented on scanapp/views.py
> +import git
What is this? If this is a new dep, add to the requirements

2017-07-23 17:49 UTC, pombredanne commented on scanapp/views.py
> +
All this code about Git should be in two functions:
1. to parse/process the url
2. to fetch.... and fetching SHOULD not be in the view ever... this should be delegated to the background task that fetches and scans

2017-07-23 17:49 UTC, pombredanne commented on scanapp/views.py
> +    template_name = 'scanapp/urlspecialscan.html'
Why would this be a special new view? When we discussed this, I said we would need a single view with a url field and not one per scan

2017-07-23 17:51 UTC, RajuKoushik commented on scanapp/views.py
> +
This has been done in the next PR. I'll try to keep this in mind.

2017-07-23 17:54 UTC, RajuKoushik commented on scanapp/views.py
> +    template_name = 'scanapp/urlspecialscan.html'
I had a discussion with @singh1114 where we planned to have a new view for the URL Scan and keep the URLSpecialScan intact for testing purposes which we would be removing after the main view is created.

2017-07-23 18:04 UTC, RajuKoushik commented on scanapp/views.py
> +
Oh ! I'll add them in 2 different functions and also make sure that fetching is delegated to the background task.

2017-07-27 07:40 UTC, pombredanne commented on scanapp/models.py
>  class CodeInfo(models.Model):
You need to rebase this pr on the latest develop with @singh1114 latest models

2017-07-27 07:41 UTC, pombredanne commented on scanapp/views.py
> +
@RajuKoushik so why not doing it now?

2017-07-31 18:16 UTC, closed without merging