Change models according to discussion at #24
nexB/scancode-server pull request #64
Opened 2017-07-22 18:53 UTC by singh1114

* Do not store the whole result in the JSONField #32
* Add docstring to the models

Signed-off-by: Ranvir Singh ranvir.singh1114@gmail.com

2017-07-24 19:55 UTC, pombredanne requested changes
See my comments. Some top level remarks: try to keep the same field names and fields order as they are in the ScanCode JSON. Also when writing a doc string for a model tells what it is or what it represents as an object not what it does as a piece of code (e.g. a model does not "stores" things, it is something or represents something).

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +    Store various attributes of a scan like `scan_type`, `is_complete`, `user`,
Do not enumerate the fields in a docstring of a model

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +        ('url', 'url'),
This can be done afterwards but we had said that we would use only one scan input, not multiple types

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +    URL = models.URLField(max_length=2000, blank=True, null=True)
Do not use uppercase for field names, even for URLs.

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +    URL = models.URLField(max_length=2000, blank=True, null=True)
You also need to add a `help=` to each fields to describe and document what they are

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>      total_code_files = models.IntegerField(null=True, blank=True)
This is a data that is best computed rather than stored.

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>      code_size = models.IntegerField(null=True, blank=True, default=0)
Same: this is best computed from the files data rather than stored

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>      scan_time = models.IntegerField(null=True, blank=True, default=0)
Would having a start_date and end_date (as Date/times types) be better? a scan time alone is not a great piece of data.

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>      total_errors = models.IntegerField(null=True, blank=True, default=0)
the total of errors is best computed and not stored

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>  class ScanFileInfo(models.Model):
This is a ScannedFile rather?

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +    """
Represent a scanned file or directory and its scanned data

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>      file_path = models.CharField(max_length=400)
Is this called `file_path` in the scan JSON? The best is to stay close to the field names used in the ScanCode output

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
> +    Stores the License information present in the code
Represent a license as detected in a file.

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
Start and end line should be best side-by-side, and try to keep the same order of the fields as they are in the ScanCode JSON.

2017-07-24 19:55 UTC, pombredanne commented on scanapp/models.py
>  class MatchedRule(models.Model):
I think that for simplicity you can use a JSONField at the License level to store a matched rule... and no specific models

2017-07-24 20:29 UTC, singh1114 commented on scanapp/models.py
>      file_path = models.CharField(max_length=400)
It is like this: "files":[{"path":"scancode-server/cc0-1.0.LICENSE"

2017-07-25 11:08 UTC, pombredanne requested changes
Thanks. See comments. For every help text, please start a sentence with a Capital letter, also check the plural vs. singular in the help texts.

2017-07-25 11:08 UTC, pombredanne commented on scanapp/models.py
> +    is_complete = models.BooleanField(default=False, help='True if the scan is completed by celery and result are stored')
Is this flag really needed? would not the presence of an end_time be enough?

2017-07-25 11:08 UTC, pombredanne commented on scanapp/models.py
> +    file_path = models.CharField(max_length=400, help='path of file scanned')
call this `path` like in a scan JSON

2017-07-25 11:08 UTC, pombredanne commented on scanapp/models.py
> +    matched_rule = JSONField(help='matched rule about the license detected')
Can you order these fields in the same order as they are in a scan JSON?

2017-07-25 11:08 UTC, pombredanne commented on scanapp/models.py
> +    author = models.CharField(max_length=200, help='copyright authors of the copyright')
Singular author, not authors

2017-07-25 12:01 UTC, singh1114 commented on scanapp/models.py
> +    file_path = models.CharField(max_length=400, help='path of file scanned')
OK.

2017-07-25 12:01 UTC, singh1114 commented on scanapp/models.py
> +    matched_rule = JSONField(help='matched rule about the license detected')
OK.

2017-07-25 12:01 UTC, singh1114 commented on scanapp/models.py
> +    is_complete = models.BooleanField(default=False, help='True if the scan is completed by celery and result are stored')
No. Not needed. I will remove it.

2017-07-25 12:01 UTC, singh1114 commented on scanapp/models.py
> +    author = models.CharField(max_length=200, help='copyright authors of the copyright')
Ok.

2017-07-25 16:25 UTC, pombredanne approved these changes
Looking good! Except for on tiny thing which the scan `__str__`. Go ahead and merge.... I did not review the code beside the models. Now after that you need to ensure that the code style pass OK.

2017-07-25 16:25 UTC, pombredanne commented on scanapp/models.py
> +        return self.scan_directory
I am not sure this is a good representation for a Scan. The URL would be better IMHO. And for an upload as opposed to a URL, then the URL could be a `file:///xxxx` URL

2017-07-25 20:27 UTC, singh1114 commented
I will try to make things better with the coding styles.

2017-07-27 06:34 UTC, merged