Fixes #69
nexB/scancode-server pull request #70
Opened 2017-07-28 08:47 UTC by singh1114

* Repair datetime format warning by using default timezone format

Signed-off-by: Ranvir Singh ranvir.singh1114@gmail.com

2017-07-31 10:30 UTC, pombredanne requested changes
Can you also add a test?

2017-07-31 10:30 UTC, pombredanne commented on scanapp/views.py
> +from django.utils import timezone
You should sort your imports

2017-07-31 12:01 UTC, singh1114 commented
What kind of changes?

2017-08-10 10:15 UTC, pombredanne approved these changes

2017-08-10 17:26 UTC, merged