Updated URLScan View
nexB/scancode-server pull request #81
Opened 2017-08-03 21:16 UTC by RajuKoushik

*Passing all the tests

Signed-off-by: Raju Koushik g.rajukoushik@gmail.com

2017-08-10 11:22 UTC, pombredanne requested changes
Thanks!
See my comments.... Are you properly synced and rebased on the latest develop?

2017-08-10 11:22 UTC, pombredanne commented on requirements.txt
> +giturl.py
Do you need a specific version?

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
>  import json
Sort your imports

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
> +    Create and save a file at `path` present at `URL` using `scan_id` and bare `path`
Where is `path`? this is not an arg?

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
> +    home_path = expanduser("~")
Saving under a user dir down not make sense. We need a well defined configured place.

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
> +    filename = home_path + '/' + clean_url + '/'
use os.path.join.

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
> +    # logic to calculate total_error
Do not keep commented out code

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
>      for a_file in json_data['files']:
a_file is not a proper variable name. Call it file or scanned_file

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
>      for a_file in json_data['files']:
do not prefix with a_ elsewhere too.

2017-08-10 11:22 UTC, pombredanne commented on scanapp/tasks.py
> +    try:
Why this try block?

2017-08-10 11:22 UTC, pombredanne commented on scanapp/views.py
>  import subprocess
sort imports

2017-08-10 18:25 UTC, RajuKoushik commented on requirements.txt
> +giturl.py
We need one. I'll update.

2017-08-10 18:27 UTC, RajuKoushik commented on scanapp/tasks.py
>  import json
Done!

2017-08-10 18:45 UTC, RajuKoushik commented on scanapp/tasks.py
> +    home_path = expanduser("~")
Sure !

2017-08-10 18:48 UTC, RajuKoushik commented on scanapp/tasks.py
> +    try:
The function which I am using to check whether it is a git url or not would return null in the case of a random absurd url but we to return the 'flag' variable every time. So the try block.

2017-08-10 18:48 UTC, RajuKoushik commented on scanapp/views.py
>  import subprocess
Sure ! Done.

2017-08-10 18:53 UTC, RajuKoushik commented on scanapp/tasks.py
> +    # logic to calculate total_error
👍

2017-08-10 18:55 UTC, RajuKoushik commented on scanapp/tasks.py
>      for a_file in json_data['files']:
Done !

2017-08-12 15:43 UTC, pombredanne requested changes
Thanks.
See my comments... There are quire a few problems that need some serious rework.

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
>  from datetime import datetime
This is not sorted?  datetime comes before json, right?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    os.chdir(home_path)
Why do you use these chdir?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    print os.curdir
why leaving print statements?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    clean_url = ''.join(e for e in url if e.isalnum())
Why do you do this?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +        shutil.rmtree(dir_name)
Never ever delete things... Why are you doing this?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    os.mkdir(dir_name)
The whole way you handle directories is broken.
You are doing a checkout. You want to get a temp directory and nothing else. Use the scancode.commoncode.fileutils code at https://github.com/nexB/scancode-toolkit/blob/22bf88df19768dd207973ed2db91249822a0c446/src/commoncode/fileutils.py#L120 and use a well defined base dir. Each new clone should go in a new temp directory. Never deleted

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    origin.pull(origin.refs[0].remote_head)
What is the magic refs[0]?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    filename = home_path + '/' + path + dir_name + '/'
Use os.path.join. Not this

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +        Parses the URL and checks if it's a git URL. If it is a git URL then the flag is set to 1.
Incorrect indentation

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +        Parses the URL and checks if it's a git URL. If it is a git URL then the flag is set to 1.
What is flag? is this something that is returned?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +def parse_url(URL):
do not use uppercase for variable and arg names

2017-08-12 15:43 UTC, pombredanne commented on scanapp/tasks.py
> +    try:
use a boolean instead. None evals to False alright.  You could replace this whole function with
`return GitURL(url).is_a('github')`
And if this is a onliner, why a function? also the doc string is misleading if you only handle github urls and not generally git-related urls

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +
Why did you move this code around? I cannot review which changes you made there

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                    file_name = str(1 + int(dir_list[-1]))
What is this code? I do not get what you are doing or trying to do with this weird thing. What is it?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                return HttpResponseRedirect('/resultscan/' + str(scan_id))
what is str(scan_id) ? why do not you use a proper attribute?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                dir_list = list()
This whole code block is weird and arcane. What are you trying to do ?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                if (str(request.user) == 'AnonymousUser'):
why the str()?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                    path = 'media/user/' + str(request.user) + '/url/'
why str()?

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                    path = 'media/user/' + str(request.user) + '/url/'
Also do not join path-lile arguments with +, use posixpath.join or url-related functions instead or even a simple '/'.join() would be better

2017-08-12 15:43 UTC, pombredanne commented on scanapp/views.py
> +                subprocess.call(['mkdir', '-p', path])
Are you serious? Calling a subprocess to create a directory? did you check the Python doc?

2017-08-13 15:56 UTC, RajuKoushik commented on scanapp/tasks.py
>  from datetime import datetime
These were actually automatically sorted by my PyCharm editor according to pep8 guidelines.

2017-08-13 15:56 UTC, RajuKoushik commented on scanapp/tasks.py
> +    os.chdir(home_path)
I am actually moving to the child directory and creating a new temp directory over there.

2017-08-13 15:58 UTC, RajuKoushik commented on scanapp/tasks.py
> +    clean_url = ''.join(e for e in url if e.isalnum())
I am trying to give the directory a name using it's url. So cleaning the scanned URL and using it as a name.

2017-08-13 15:59 UTC, RajuKoushik commented on scanapp/tasks.py
> +        shutil.rmtree(dir_name)
Sure ! I'll try a better way out if the directory already exists.

2017-08-15 09:47 UTC, pombredanne requested changes
See my comments... This would need some tests too :P

2017-08-15 09:47 UTC, pombredanne commented on scanapp/models.py
>          max_length=200,
Are you sure a path cannot be longer than this?

2017-08-15 09:47 UTC, pombredanne commented on scanapp/tasks.py
> +from giturl import *
never import * and sort your imports: g comes after d

2017-08-15 09:47 UTC, pombredanne commented on scanapp/tasks.py
> +        logger = logging.getLogger(__name__)
The logger creation should be top level. Not inside a function

2017-08-15 09:47 UTC, pombredanne commented on scanapp/tasks.py
> +        logger.info('git repo detected')
a  log entry should contain more details, e.g. information about the args used (here the host at least)

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
> +from giturl import *
No import * please

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
> +
Empty line not needed here?

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
No empty line here

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
>  from django.views.decorators.csrf import csrf_exempt
Django imports should go with the thirdparty, before you scanapp import (e.g. 4 blocks: 1. `__*` imports, 2. stdlib imports, 3. thirdparty imports, 4. own code imports)

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
> +            if str(request.user) == 'AnonymousUser':
Do not use str() ... not here and almost nowhere. Use the attribute (e.g. here likely reques.user.name ?)

2017-08-15 09:47 UTC, pombredanne commented on scanapp/views.py
> +                path = '/'.join([''.join([path, str(scan_id)]), file_name])
no str()

2017-08-15 09:50 UTC, singh1114 commented on scanapp/tasks.py
> +from giturl import *
It was given in the documentation of giturl. 
https://github.com/willyg302/giturl#usage

2017-08-15 10:02 UTC, singh1114 commented on scanapp/models.py
>          max_length=200,
Ok, can we change it to 2000.

2017-08-15 10:04 UTC, singh1114 commented on scanapp/tasks.py
> +        logger = logging.getLogger(__name__)
Yes! Done.

2017-08-15 18:17 UTC, singh1114 commented on scanapp/views.py
> +            if str(request.user) == 'AnonymousUser':
`"Scan.user" must be a "User" instance.` Error produced after removing `str`

2017-08-15 18:17 UTC, singh1114 commented on scanapp/views.py
> +                path = '/'.join([''.join([path, str(scan_id)]), file_name])
`sequence item 1: expected string or Unicode, int found`
found this error after removing `str`. Is there any method to take care of this.

2017-08-15 21:26 UTC, RajuKoushik commented on scanapp/views.py
> +                path = '/'.join([''.join([path, str(scan_id)]), file_name])
Done ! Used the format() function instead.

2017-08-17 09:58 UTC, pombredanne commented on scanapp/tasks.py
> +import requests
request starts with r and goes after g ;)

2017-08-17 09:59 UTC, pombredanne commented on scanapp/views.py
> +from giturl import *
No import * please. Use exactly what you need and no more

2017-08-17 11:31 UTC, merged